preview: '@preview-card'
default: Overview
context:
  class: 'mzp-has-aspect-3-2'
  link: https://example.com
  image: '/img/image-3-2.jpg'
  tag: Card tag
  title: Card title with about 30-40 characters
  desc: A description of about 150 characters, give or take. That means we usually only have room for one or two sentences. Here is what that looks like.
  cta: Call to action
  meta: Card meta info
variants:
  - name: Small
    context:
      class: 'mzp-c-card-small mzp-has-aspect-1-1 mzp-has-audio'
      link: https://example.com
      image: '/img/image-1-1.jpg'
      tag: Audio
      title: Card title with about 30-40 characters
      desc: A description of about 150 characters, give or take. That means we usually only have room for one or two sentences. Here is what that looks like.
      cta: This call to action is 37 characters
      meta: false
    notes: |
      - Small sized cards can contain images with 16:9, 3:2 or 1:1 aspect ratios.
      - The card in this example displays an icon next to the card tag name, to
        indicate the media type that may be played on click.
      - Headlines should be a maximum of 50 characters, and descriptions a
        maximum of 150 characters.
  - name: Medium
    context:
      class: 'mzp-has-aspect-3-2 mzp-has-video'
      image: '/img/image-3-2.jpg'
      tag: Video
      meta: false
    notes: |
      - Medium is the default card size.
      - Medium sized cards can contain images with 16:9, 3:2 or 1:1 aspect ratios.
      - The card in this example displays an icon next to the card tag name, to
        indicate the media type that may be played on click.
      - The card in this example includes an optional inline call to action.
        Inline CTAs should only be used with a description.
      - Headlines should be a maximum of 50 characters, and descriptions a
        maximum of 150 characters.
  - name: Large
    context:
      class: 'mzp-c-card-large mzp-has-aspect-16-9'
      image: '/img/image-16-9.jpg'
      tag: false
      cta: false
      meta: false
    notes: |
      - Large sized cards display larger text than other card types.
      - Large sized cards should contain images with 16:9 or 3:2 aspect ratios
        only.
      - Headlines should be a maximum of 50 characters, and descriptions a
        maximum of 150 characters.
  - name: Dark Theme
    preview: '@preview-card-dark'
    notes: Cards will inherit a dark theme from an ancestor with the class `mzp-t-dark`.
