context:
  label: Primary Button
default: Primary
variants:
  - name: Using link
    notes: CTA anchor styled as Button.
    context:
      link: './button--using-link'
  - name: Primary Dark
    preview: '@preview-dark'
    notes: Add the class `mzp-t-dark` for use on dark backgrounds (the button itself is light).
    context:
      class: 'mzp-t-dark'
      link: './button--primary-dark'
  - name: Secondary
    notes: A less prominent button with a hollow, transparent background. Use this for any additional actions someone can take on any given page that is different from the primary action.
    context:
      class: 'mzp-t-secondary'
      label: Secondary Button
      link: './button--secondary'
  - name: Secondary Dark
    preview: '@preview-dark'
    notes: A light variation of the secondary button for dark backgrounds, adding the class `mzp-t-dark` (the button itself is light).
    context:
      class: 'mzp-t-secondary mzp-t-dark'
      label: Secondary Button
      link: './button--secondary-dark'
  - name: Product
    notes: Use this theme style for product-related transactions, such as downloading software or creating an account.
    context:
      class: 'mzp-t-product'
      label: Download Firefox
      link: './button--product'
  - name: Product Secondary
    notes: This secondary product button theme should be used when the CTA is a product-related transaction, but not the main action a person should take on a page.
    context:
      class: 'mzp-t-product mzp-t-secondary'
      label: Download Firefox
      link: './button--product-secondary'
  - name: Product Secondary Dark
    preview: '@preview-dark'
    notes: A light variation of the secondary product button for use on dark backgrounds. Add the class `mzp-t-dark` (the button itself is light).
    context:
      class: 'mzp-t-product mzp-t-secondary mzp-t-dark'
      label: Download Firefox
      link: './button--product-secondary-dark'
  - name: Neutral
    notes: A neutral button for less important actions.
    context:
      class: 'mzp-t-neutral'
      label: Neutral Button
      link: './button--neutral'
  - name: Neutral Dark
    preview: '@preview-dark'
    notes: A light variation of the neutral button for use on dark backgrounds. Add the class `mzp-t-dark` (the button itself is light).
    context:
      class: 'mzp-t-neutral mzp-t-dark'
      label: Neutral Button
      link: './button--neutral-dark'
  - name: Disabled
    notes: |
      This is an example of a disabled button. The `disabled` property is added on submit to
      prevent people from submitting their information twice while submitting a form.
      Or it can be removed dynamically when a form is completed, to prevent a user from
      submitting before they've filled out all required fields.
    context:
      label: Disabled Button
      disabled: True
