preview: '@preview-unpadded'
default: Overview
variants:
  - name: Half
    notes: |
      The class `mzp-l-card-half` sets up a two-column layout so it's best for
      even numbers of cards. Use large sized cards if the container is
      wide, or small or medium cards in narrower containers.
  - name: Third
    notes: |
      The class `mzp-l-card-third` sets up a three-column layout so cards should
      come in multiples of three to avoid empty spaces when cards wrap to new rows.
      At some medium breakpoints the layout will form two columns and an empty space
      may be unavoidable. This layout really works best with six cards so it avoids
      gaps at all widths (two rows of three or three rows of two).

      ### Tips
      - Use medium sized cards.
      - Avoid using a three-column layout in narrow containers.
  - name: Quarter
    notes: |
      The class `mzp-l-card-quarter` sets up a four-column layout so cards should
      come in multiples of four to avoid empty spaces when cards wrap to new rows.

      ### Tips
      - Use small sized cards.
      - Avoid using a four-column layout in narrow containers.
  - name: Hero
    notes: |
      The class `mzp-l-card-hero` sets up a five-card layout with one large hero card.

      - In small viewports cards stack vertically and span the full container width.
      - In medium sized viewports the first card spans the full width and the remaining four
        cards each span half widths.
      - In large viewports the first card spans two thirds and the remaining cards each span
        one third.

      The first card in this arrangement should be large sized with a 16:9 aspect ratio image.
      The other cards should all be medium sized.
